version: '3.8'

services:
  spring-boot:
    build:
      context: .
      dockerfile: ./Dockerfile  # Specify the path to your Dockerfile here
    ports:
      - "2001:2001"
    depends_on:
      - mysql
    environment:
      - SPRING_APPLICATION_NAME=OMSVC
      - SERVER_PORT=2001
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/projectdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_MVC_VIEW_PREFIX=/
      - SPRING_MVC_VIEW_SUFFIX=.jsp
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projectdb  # Ensure this is in key-value format
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
